//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        public int BillingDetailID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
