//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int RelationshipID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ChildID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
